### ISSUE TITLE
Corsair iPSU Support?

### ISSUE THREAD

**Issue by mikihacia** [tobinbrooke/icue2mqtt#12]
Will this repo support PSUs of i-series (These have power usage exposed to the iCUE)?
That might be handy to see how much power PC was dragging over past day or month.

![image](https://user-images.githubusercontent.com/52580946/138568155-098d1117-5b27-42c0-ad45-f5c7cc35b9d1.png)

**Comment by tobinbrooke** [comment]
unfortunately, no. It uses the iCue SDK which does not expose any sensor readings and is (at last check) only intended to control lights. I did have a look to see if there is any way to access sensor readings but not had much luck.
