### ISSUE TITLE
asus gpu issue not showing up in HA

### ISSUE THREAD

**Issue by ideal2545** [tobinbrooke/icue2mqtt#13]
Hey, love this addon, one 'unintended feature' is that asus GPU's aren't showing up in HA, im wondering if its the unique having a colon in the name? 

```
{
  "name":"ASUS GPU: Vga 1",
  "unique_id":"ASUS_GPU:_Vga_1",
  "platform":"mqtt_json",
  "state_topic":"homeassistant/light/icue2mtt/ASUS_GPU:_Vga_1/state",
  "command_topic":"homeassistant/light/icue2mtt/ASUS_GPU:_Vga_1/set",
  "schema":"json","rgb":true,
  "optimistic":false,
  "qos":0
}
```

Also just as a suggestion I believe if you stick all the topics under one manufacturer in HA they show up nicely in one place for easier seeing of entities

**Comment by tobinbrooke** [comment]
Its probably not in the iCue SDK as I just enumerate over the devices that
expose.

**Comment by tobinbrooke** [comment]
I don't have a asus GPU to try it with. As soon as I get some time I'll just remove any colons from entity names to see if that solves it

**Comment by tobinbrooke** [comment]
I have the asus MB working with the integration though the Asus software itself is tempermental. I have not had any further details so closing the issue
