### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by ugubser** [tobinbrooke/icue2mqtt#15]
Hello, 

I have followed the guide, set the correct IP address and login, password for my Mosquitto MQTT broker (which is also where Homeassistant connects to), compiled it and installed as a service. When I start it, nothing happens. Further, I don't see a log file being generated. I have left the defaul logfile path (C:\temp) but nothing is being created. I'm not new to software development but I'm new to Windows development (Windows 11). What am I missing? Any advise? 

My iCue install is 4.18.209 and I've enabled plugins

Thanks

**Comment by tobinbrooke** [comment]
Hi, do you see anything in the windows logs?

**Comment by tobinbrooke** [comment]
Are you using home assistant and a MQTT broker? Are you familiar with the matt auto discovery on HA? When you open windows services does the icue2mqtt service show as running?

**Comment by ugubser** [comment]
Hi,

so, yes the service is running and I've managed to find the logs (pasted below, sorry for the spam). I see one error returning a devicelist from SDK 
 ("SDK error getting list of devices: InvalidArguments") but then it still says it publishes name of devices to MQTT. It also says it's connected to MQTT - under what topics is this published? 

Yes, I use homeassistant and no, I'm not that familiar with the auto discovery feature. I actually only have one other topic besides homeassistant (zigbee2mqtt) for which the autodiscovery in homeassistant seems to be working very well. 




Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device VENGEANCE RGB PRO
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5163493Z" />
    <EventRecordID>2174</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device VENGEANCE RGB PRO</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device PRESTIGE X570 CREATION
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5163493Z" />
    <EventRecordID>2175</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device PRESTIGE X570 CREATION</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device MM800RGB
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5158512Z" />
    <EventRecordID>2172</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device MM800RGB</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device VENGEANCE RGB PRO
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5158512Z" />
    <EventRecordID>2173</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device VENGEANCE RGB PRO</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device K70 RGB MK.2
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5153485Z" />
    <EventRecordID>2171</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device K70 RGB MK.2</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device H100i PLATINUM
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5148508Z" />
    <EventRecordID>2169</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device H100i PLATINUM</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device M65 PRO RGB
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.5148508Z" />
    <EventRecordID>2170</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device M65 PRO RGB</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Publishing device Lighting Node Pro
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.4923479Z" />
    <EventRecordID>2168</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Publishing device Lighting Node Pro</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
SDK error getting list of devices: InvalidArguments 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.4913478Z" />
    <EventRecordID>2167</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>SDK error getting list of devices: InvalidArguments 
</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Connected to MQTT broker
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.4633509Z" />
    <EventRecordID>2166</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Connected to MQTT broker</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Connecting to MQTT broker
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.4213512Z" />
    <EventRecordID>2165</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Connecting to MQTT broker</Data>
  </EventData>
</Event>

Log Name:      icue2mqttLog
Source:        icue2mqtt
Date:          1/6/2022 9:00:26 PM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      BFG-Ryzen
Description:
Starting
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="icue2mqtt" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-06T20:00:26.4138507Z" />
    <EventRecordID>2164</EventRecordID>
    <Correlation />
    <Execution ProcessID="27312" ThreadID="0" />
    <Channel>icue2mqttLog</Channel>
    <Computer>BFG-Ryzen</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Starting</Data>
  </EventData>
</Event>

**Comment by tobinbrooke** [comment]
Interesting that it seems to publish the devices. It does not list them as
a matt device but as individual matt entities under the matt integration in
ha. I will have to get back to you on the topic it uses

**Comment by harrisonhjones** [comment]
I wanted to +1 this issue with my own experience. I installed icue2mqtt as per the instructions in the readme though I did NOT copy the release to a separate folks. I left it in `C:\Users\harri\Documents\icue2mqtt\icue2mqtt\bin\Release\netcoreapp3.1\win-x64`. I updated properties.json to:

```json
{
  "logPath": "C:\\Users\\harri\\Documents\\icue2mqtt\\icue2mqtt\\bin\\Release\\netcoreapp3.1\\win-x64\\service-log.txt",
  "mqttCredentialsPwd": "REDACTED",
  "mqttCredentialsUser": "u'REDACTED_USERNAME",
  "mqttUrl": "homeassistant.local"
}
```

And successfully installed and started the service. Here's where I run into trouble:
1. I do _not_ see any new devices added to HASS
1. I do _not_ see a `service-log.txt` anywhere.
1. I do see 
    ```text
    1643078042: New client connected from XXX.XXX.XXX.XXX as REDACTED (p2, c1, k15, u'REDACTED_USERNAME').
    ```
    In the mqtt logs
1. I see `Connected to MQTT broker` in the Windows Event Viewer

It's been about 30 minutes and there is no change. No new logs, no discovered, device, nothing. What are the next steps in the debugging process?

**Comment by tobinbrooke** [comment]
As this is a windows service, to debug it I added a if statement to bypass the service and make it run as a console application. When looking to debug just change the
if (true) to if (false) on the Program.cs which will cause it to run as a normal application and be debuggable in visual studio.

Currently, the system is designed to log to the Windows event log. The log path is only used if it fails to get access to the event log. Additionally, it will log to file when running as a console app for debugging.

It is worth noting the devices will not appear as devices in HASS but as individual entities

**Comment by harrisonhjones** [comment]
So I would just change https://github.com/tobinbrooke/icue2mqtt/blob/master/icue2mqtt/Program.cs#L11 to be `if (true)`, recompile, and re-run?

**Comment by tobinbrooke** [comment]
that is correct if you are looking to debug it. I'll eventually move that to a property

**Comment by tobinbrooke** [comment]
no further response assume debugging worked
