### ISSUE TITLE
ICUE4 Suppory

### ISSUE THREAD

**Issue by franco-101** [tobinbrooke/icue2mqtt#17]
Hello,
Does this work with iCUE4?
I have followed the guide and can see the service connecting to the broker but no devices are discovered any ideas?
Thanks

**Comment by tobinbrooke** [comment]
Yes it works with iCUE4. The devices do not show up as devices but individual entities

**Comment by franco-101** [comment]
Thanks for your reply I managed to get it partially working. 
The issue I have now is that when the state of the lights change, it doesn’t send update to home assistant. Have to restart service for state change to be sent.
