### ISSUE TITLE
Entity State not updating in HA

### ISSUE THREAD

**Issue by franco-101** [tobinbrooke/icue2mqtt#19]
Hello

The issue I have is that when the state of the lights change, via profile or manual change. It doesn’t send the update to home assistant. I have to restart the service for the state to change.

**Comment by tobinbrooke** [comment]
yeah, unfortunatly that is a limitation of the icue SDK. You either need to take control in which case it overrides the iCue application or relinquish control back to iCue in wich case you cannot find the state. I could potentially experiment with some form of polling where I request control to get the state and then release but may case the scenes to flicker off not sure. Currently If you have control it gets the state then it just sends updates when you make changes through this tool so no regular polling
