### ISSUE TITLE
Should i worry?

### ISSUE THREAD

**Issue by MADS0LADEN** [tobinbrooke/icue2mqtt#2]
Should i worry about this warning? :)
https://i.imgur.com/vB2Ev4g.png

**Comment by tobinbrooke** [comment]
No I get it too. I normally run the command twice. The second time I do not get the message but I think even with the message the build still works. Fyi I am having some stability issues with the mqtt package and will investigate a alternative today

**Comment by tobinbrooke** [comment]
This is a unreachable line only accessible when we set it to debug mode to allow it to run as a console app instead of a service. Shouldn't be an issue. PS: today's update uses a MQTT client which looks more stable

**Comment by tobinbrooke** [comment]
not a issue is unused line to allow debugging as a console app
