### ISSUE TITLE
services.msc error

### ISSUE THREAD

**Issue by fredycz2005** [tobinbrooke/icue2mqtt#22]
hello when i try to start icue2mqtt windows says that he can not find that file.

**Comment by tobinbrooke** [comment]
I'm going to need more to go on. What steps did you take? What is in the logs?

**Comment by fredycz2005** [comment]
i did all the steps for installation as you write it down and i do not know how to see logs.

**Comment by fredriksvahn** [comment]
@fredycz2005 Event Viewer > Applications and Services Logs > icue2mqttLogs
