### ISSUE TITLE
I got a problem.

### ISSUE THREAD

**Issue by lindberg87** [tobinbrooke/icue2mqtt#4]
It looks like that Corsair icue are out of run, and the new Corsair Link is taken over all corsair devices.... 
I can no longer use this icue2mqtt mod to take control on my corsair strip light.... Are there coming a update for this mod/code to support the newer Corsair Link program ? 

Best Regards Stig

**Comment by tobinbrooke** [comment]
Hi, do you mean a new version of the iCue commander hardware? I am not sure of the problem as I updated my iCue software to the latest version and it still seems to work. If its new hardware that is incompatible with the iCue SDK I am not sure how to test this without doing a substantial hardware investment

**Comment by crookedview** [comment]
I believe Corsair Link is the older software, and iCUE is the replacement.
